### ISSUE TITLE
How can we re-verify?

### ISSUE THREAD

**Issue by minkyn** [starkscan/starkscan-verifier#1]
I have two files (call them A.cairo and B.cairo) with exactly the same content. I accidentally verified an A contract with B.cairo code. Although they share the same content, Starkscan will show B as the name and B.cairo as the file name under the **Class**->**Class Code** section.

Current `starkscan` command doesn't allow re-verification.

**Comment by 0xmonkeyy** [comment]
@minkyn there's no way to re-verify right now. What's the contract address? And for which network? I can help unverify it

**Comment by minkyn** [comment]
I ended up changing the code a bit to get a new class hash to verify, and didn't keep a record of the old contract address.

Good to know you have a way to un-verify it, in case for a future file renaming need.

I'll close this one for now. Thanks.
